version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker-files/php-fpm/Dockerfile
      args:
        UID: "${USER_ID}"
        GID: "${GROUP_ID}"
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www
    depends_on:
      - postgres
      - redis
    networks:
      - telegram_bot

#порты определяются в docker-compose.override
  nginx:
    build:
      context: .
      dockerfile: docker-files/nginx/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./public:/var/www/public
      - ./docker-files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-files/nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./docker-files/nginx/privkey.pem:/etc/nginx/privkey.pem
    depends_on:
      - php-fpm
    networks:
      - telegram_bot

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: telegram_db
    volumes:
      - .:/var/lib/postgresql/data
    networks:
      - telegram_bot

  redis:
    image: redis:7.0.4
    networks:
      - telegram_bot
networks:
  telegram_bot:
    external:
      name: telegram_bot