version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker-files/php-fpm/Dockerfile
      args:
        UID: "${USER_ID}"
        GID: "${GROUP_ID}"
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www

#порты определяются в docker-compose.override
  nginx:
    build:
      context: .
      dockerfile: docker-files/nginx/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./public:/var/www/public
      - ./docker-files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-files/nginx/fullchain.pem:/etc/nginx/fullchain.pem
      - ./docker-files/nginx/privkey.pem:/etc/nginx/privkey.pem
    depends_on:
      - php-fpm

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: game
    ports:
      - '5432:5432'

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
