version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker-files/php-fpm/Dockerfile
      args:
        UID: "${USER_ID}"
        GID: "${GROUP_ID}"
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www

  nginx:
    build:
      context: .
      dockerfile: docker-files/nginx/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./public:/var/www/public
      - ./docker-files/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm

  certbot:
    container_name: service_certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

#  postgres:
#    image: postgres:9.6-alpine
#    container_name: postgres
#    environment:
#      POSTGRES_USER: db_user
#      POSTGRES_PASSWORD: db_password
#      POSTGRES_DB: game
#    ports:
#      - '5432:5432'
